

build:
  env:
    NODE_VERSION: 18

services:
  - type: web
    name: police-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URI
        fromEnvVar: MONGO_URI
      - key: JWT_SECRET
        fromEnvVar: JWT_SECRET
      - key: PORT
        fromEnvVar: PORT
