



services:
  - type: web
    name: police-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URI
        fromEnv: MONGO_URI
      - key: JWT_SECRET
        fromEnv: JWT_SECRET
      - key: PORT
        fromEnv: PORT
    nodeVersion: 18
